### PR TITLE
Added healthcheck

### PR DESCRIPTION
**Pull request by nikorev**
Small change, healthcheck simply does a curl for the http header to see Cyberchef return a 200 OK status.

### CODE REVIEW

**Comment by mpepping** [comment]
Thanks for the PR, @nikorev! Please give me a moment to test if this solution also works on IPv6 native/only hosts.

**Comment by nikorev** [comment]
I didn't even think about ipv6! We can fallback to an ipv6 based address in a second curl request if the first one fails. Here's a snippet of the bash command.

`[ $(curl -I -s http://127.0.0.1:8000 | head -n 1 | cut -d' ' -f2 | head -n 1) -eq 200 ] || [ $(curl -I -s -6 http://[::1]:8000 | head -n 1 | cut -d' ' -f2 | head -n 1) -eq 200 ] || exit 1`

Also depending on the curl version included in the container, the ipv6-based command may need to be tweaked. I'll test before updating the branch.

**Comment by mpepping** [comment]
Thanks for updating the PR, @nikorev! After [reading up on how curl handles `localhost` nowadays](https://daniel.haxx.se/blog/2021/05/31/curl-localhost-as-a-local-host/), maybe this can work as well .. what do you think?

```bash
HEALTHCHECK --interval=30s --timeout=3s --start-period=10s --retries=3 \
    CMD curl -sf -o /dev/null -w "%{http_code}" http://localhost:8000 || exit 1
```

**Comment by nikorev** [comment]
Interesting, the container has curl v8.4.0 meaning we can take advantage of the hardcoded localhost address. Great find! Let's do that.

As for the command, we're already suppressing output with `-s` and redirecting output to null with `-o /dev/null`, so the `-w "%{http_code}"` portion of the command is unnecessary. The weird chain of piping to `head` and `cut` in my previous commits was to ensure the status code was specifically 200. This is required in certain situations, but since this website doesn't require authentication, using `-f` should be fine in this case. My reasoning behind this is explained within curl's man page below. `-f` will have the curl command return non-zero if the http request fails.

image

While curl will return 0 on success (which is compliant with Docker's healthcheck), curl can return multiple potential non-zero results on failure (https://everything.curl.dev/usingcurl/returns) while Docker only expects 1, so we'll still have to do the `|| exit 1` portion.

I've tested the following simplified healthcheck and will be pushing up a commit shortly. Feel free to stick with this one or rollback to the previous one.

```
HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
    CMD curl -sf -o /dev/null http://localhost:8000 || exit 1
```

**Comment by mpepping** [comment]
Thanks for both the PR and the opportunity to learn something new, @nikorev! Very much appreciated!

**Comment by nikorev** [comment]
Of course!

**Pull request merged**
